### ISSUE TITLE
can CodeBERT be used to transform NL to DSL code?

### ISSUE THREAD

**Issue by sharaku17** [microsoft/CodeBERT#66]
Hello, 

I have the following issue:
I have a Corpus of a multitude of system requirements given in a natural language. An example requirement can look like this:

`When the Gear shifter is put into Drive, the Car should start moving forward!`

my task was to develop a Domain specific language (DSL) that models these NL requirements. I have developed certain keywords in my DSL and the requirement above translated in my DSL would look like this:

```
The Component: Gear shifter
    if: put into Drive 
    then: Car should start moving forward
```

The keywords in this case would be "The Component", "if" & "then" (of course there are some more but in this example this ones would suffice)

So my Goal is essentially to transform the NL requirement into the DSL requirement. Is it possible to fine-tune or train CodeBERT in regard to my developed DSL ?

**Comment by guoday** [comment]
CodeBERT can be used to transform NL to DSL code. But CodeBERT only serves as the encoder. However, the input of your corpus is NL instead of programming language. Therefore, using RoBERTa could be better.

**Comment by sharaku17** [comment]
Oh okay! So if I would use CodeBERT or RoBERTa as the encoder, would you know which model would be more suitable as the decoder for the actual text generation? I first thought about GPT 2 but in my experience, that model is better suited for blog-post-like text and does not so well for highly structured text like programming code or in my case DSL code. Is that right ?

**Comment by guoday** [comment]
If you want to use CodeBERT or RoBERTa as the encoder, the decoder must be randomly initialized, like code summarization in this repo, because there's not specific decoder for DSL. For GPT2, you don't need decoder since the encoder and decoder of GPT2 are same. I think GPT2 is better for you, since your input is NL (that is suitable for GPT2) and your task is generation (that is also suitable for pretraining task of GPT2). 

Two suggestions to improve:
1. You can find a model which is pre-trained on the DSL you need in [here](https://huggingface.co/models).
2. You can continue to pre-train GPT2 on DSL data and then fine-tune on the NL->DSL task.
