### ISSUE TITLE
Use CodeBERT to get source code embeddings

### ISSUE THREAD

**Issue by Avra2** [microsoft/CodeBERT#90]
Hello,

Thank you for this work. Can you pleas give some steps how to use your model to get source code embeddings only. Like suppose we have 1000 files for Python. Then for each file (might have classes and methods) we are interested to get the file embeddings. Can you please show if this is possible and give us some steps how to do that? 

Thank you.

**Comment by guoday** [comment]
please refer to https://github.com/microsoft/CodeBERT#nl-pl-embeddings

**Comment by 193769981** [comment]
Hello,

Thank you for this work.
I can use "context_embeddings=model(torch.tensor(tokens_ids)[None,:])[0]" to get ccontext_embeddings, and then when I change 0 to 1, I should get cls_ embedding, but cls_ embeddings and context_ embeddings [0] are not the same. Is this correct, thank you!
![image](https://user-images.githubusercontent.com/44664739/145145317-ad259a9b-8c57-466f-b709-d3d56086968e.png)

**Comment by guoday** [comment]
`context_ embeddings [0]`  is the cls embedding. `model(torch.tensor(tokens_ids)[None,:])[1]` applies a linear layer to cls embedding.

**Comment by 193769981** [comment]
Thanks！


---Original---
From: &quot;Daya ***@***.***&gt;
Date: Wed, Dec 8, 2021 12:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/CodeBERT] Use CodeBERT to get source code embeddings (Issue #90)




 
context_ embeddings [0]  is the cls embedding. model(torch.tensor(tokens_ids)[None,:])[1] applies a linear layer to the cls embedding.
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
